### ISSUE TITLE
Update recruitment information

### ISSUE THREAD

**Issue by tsalo** [NBCLab/NBCLab.github.io#13]
The recruitment information on the [old site](http://neurolab.fiu.edu/tools/) is outdated by a couple of years. Currently, we have that section empty on the [new site](https://nbclab.github.io/contact.html#join), but we need updated information to put up.

**Comment by tsalo** [comment]
@angielaird @masuther Are we looking for any graduate students, post-docs, RAs, etc. at the moment?

**Comment by angielaird** [comment]
Yes to physics grad students, maybe to psychology grad students, yes to an ABCD RA, no to postdoc (unless we get a great applicant).

**Comment by tsalo** [comment]
This should be largely addressed by #18.
