### ISSUE TITLE
Standardize aspect ratio for profile pictures on Team page

### ISSUE THREAD

**Issue by tsalo** [NBCLab/NBCLab.github.io#250]
Requested by @angielaird. Some possible solutions:

1. Require everyone to provide pictures with the same shape. Not easily enforceable and requires more oversight from a website czar than anyone would like.
    - I guess we could add tests and use continuous integration though.
2. Resize images automatically. Will probably result in smooshed pictures, at first.
3. Automatically show the correctly-sized center of each image. Will probably result in missing faces, at first.

In any case, folks really will need to preview their changes before opening PRs.

**Comment by angielaird** [comment]
Delighted to be the web czar! Everyone should please resize your images to be 200 pixel x 200 pixel (300dpi). If you do not have software to do this, please email me your picture and I'll resize and send back.

**Comment by tsalo** [comment]
I've added a continuous integration step to check the sizes of the images.

**Comment by tsalo** [comment]
The resizing and cropping is handled in #252, so I'm going to close this. If anyone wants to update their profile photo, they can open a PR.
